### ISSUE TITLE
Fix events section

### ISSUE THREAD

**Issue by Alcatraz9** [Machine-Learning-for-Everyone-ML4E/ML4E-website#7]
Make the section responsive and add better styling if possible

**Comment by christinablakely** [comment]
I'd like to work on this one. :)

**Comment by Alcatraz9** [comment]
> I'd like to work on this one. :)

Glad to hear it. Go ahead and make necessary changes and make a PR. We will review it.😀

**Comment by himanshubobade** [comment]
@Alcatraz9 can you assign me this task??

**Comment by Alcatraz9** [comment]
was fixed in #13
